In [24]:
import numpy as np
from numpy import random
arr=random.randint(20,size=(4,5))
print(arr)
arr_zeroes=np.zeros(10)
print(arr_zeroes)
arr_ones = np.ones(10)
print(arr_ones)
arr_five=np.full(10,5)
print(arr_five)
array_even = np.arange(10, 51, 2)
print(array_even)
random_number = np.random.rand()
print(random_number)

np.savetxt("matrix.txt",arr,fmt='%d', delimiter=',')

[[18  3  3  2  5]
 [ 4  4  7  4 18]
 [12 11 18 19  0]
 [16  6 16 10 15]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
0.29530895013530545
