In [7]:
import numpy as np
row =int(input("enter the number of elements for the row"))
column = int(input("enter the number of elements for the column"))
data=[]
for i in range(row):
    row = list(map(int, input(f"Enter row {i + 1} elements separated by spaces: ").split()))
    data.append(row)
arr=np.array(data)
arr_transpose=arr.transpose()
arr_flatten=arr.flatten()
print(arr)
print("transpose of the matrix")
print(arr_transpose)
print("flattened matrix")
print(arr_flatten)



enter the number of elements for the row 2
enter the number of elements for the column 3
Enter row 1 elements separated by spaces:  1 2 3
Enter row 2 elements separated by spaces:  2 3 4


[[1 2 3]
 [2 3 4]]
transpose of the matrix
[[1 2]
 [2 3]
 [3 4]]
flattened matrix
[1 2 3 2 3 4]
