In [77]:
import numpy as np
import random

n=int(input("Enter value of n:"))
numbers=list(range(n*n))
random.shuffle(numbers)

puzzle = np.array(numbers).reshape(n,n)
print("Generated", n, "×", n, "puzzle:")
for row in puzzle:
    print(row)

Enter value of n: 3


Generated 3 × 3 puzzle:
[3 8 0]
[2 7 5]
[6 1 4]


In [ ]:
def goal_test(puzzle):
   n=puzzle.shape[0]
   goal=np.arange(1,n*n)
   goal=np.append(goal,0)
   return np.array_equal(puzzle.flatten(), goal)
    

In [101]:
import collections
def find_zero(state):
    return tuple(np.argwhere(puzzle == 0)[0])
            
def move_tile(puzzle,direction):
   row,col=find_zero(puzzle)
   new_puzzle=puzzle.copy()
   if direction=="up" and row>0:
      new_puzzle[row,col],new_puzzle[row-1,col]=new_puzzle[row-1,col],new_puzzle[row,col]

   elif direction=="down" and row<n-1:
        new_puzzle[row,col],new_puzzle[row+1,col]=new_puzzle[row+1,col],new_puzzle[row,col]
    
   elif direction=="left" and col>0:
        new_puzzle[row,col],new_puzzle[row,col-1]=new_puzzle[row,col-1],new_puzzle[row,col]

   elif direction=="right" and col<n-1:
        new_puzzle[row,col],new_puzzle[row,col+1]=new_puzzle[row,col+1],new_puzzle[row,col]
   else :
      return None
   return new_puzzle



In [103]:
import collections
def bfs_solve(puzzle):
     queue=collections.deque(puzzle)
     visited=set()
     all_states=[]
     while queue:
       current_state=queue.popleft()
       state_tuple = tuple(current_state.flatten())
       if state_tuple in visited:
            continue
       visited.add(state_tuple)
       all_states.append(current_state)
       for move in ["left", "right", "up", "down"]:
            new_state = move_tile(current_state, move)
            if new_state is not None and tuple(new_state.flatten()) not in visited:
                queue.append(new_state)


In [105]:
bfs_solve(puzzle)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed