In [75]:

import numpy as np
arr=np.array(
    [
        [1,2],
        [3,4],
        [5,6]
    ]
)
U,S,VT=np.linalg.svd(arr)
print(U)
print(S)
print(VT)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
